// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAImJX0UE71WA_HKmsfnnjqH3hmsBpOWkk',
    appId: '1:370326310795:web:99333684b296fff345a98e',
    messagingSenderId: '370326310795',
    projectId: 'todo-be7cb',
    authDomain: 'todo-be7cb.firebaseapp.com',
    storageBucket: 'todo-be7cb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW9UdC9TWSMUcOlOy7qNNn7_XV7qofjHI',
    appId: '1:370326310795:android:d1029492bab11daa45a98e',
    messagingSenderId: '370326310795',
    projectId: 'todo-be7cb',
    storageBucket: 'todo-be7cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpTYUZobWKWdd5RDAUKR_iQTTU_ZveSz8',
    appId: '1:370326310795:ios:c7dce7e44d9191fc45a98e',
    messagingSenderId: '370326310795',
    projectId: 'todo-be7cb',
    storageBucket: 'todo-be7cb.appspot.com',
    iosBundleId: 'com.example.toDoApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpTYUZobWKWdd5RDAUKR_iQTTU_ZveSz8',
    appId: '1:370326310795:ios:09657b115f9ac53345a98e',
    messagingSenderId: '370326310795',
    projectId: 'todo-be7cb',
    storageBucket: 'todo-be7cb.appspot.com',
    iosBundleId: 'com.example.toDoApplication.RunnerTests',
  );
}
